services:
  - type: web
    name: onix-racing
    runtime: node
    repo: https://github.com/DylanRamirezLopez/onix-racing
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
